"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const steps = [["Company", "Tell us who we will be supporting."], ["Industry", "Help us understand your operating environment."], ["Training", "Choose the capability area you want to strengthen."], ["Participants", "Give us an initial indication of workforce size."], ["Location", "Tell us where delivery may take place."], ["Preferred date", "Share your preferred timing."], ["Review", "Check the information before submitting."]];
const industries = ["Oil & Gas", "Petrochemical", "Construction", "Manufacturing", "Marine & Offshore", "Power & Utilities", "Government & GLC", "Others"];
const categories = ["Industrial Safety", "Technical Competency", "Industrial Consultancy", "Workforce Development"];

export default function ProposalWizard() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [values, setValues] = useState({ companyName: "", contactPerson: "", jobTitle: "", email: "", phone: "", industry: "", category: "", programme: "", participants: "", location: "", month: "", budget: "", objectives: "", notes: "", consent: false });
  const [errors, setErrors] = useState({});
  const [status, setStatus] = useState({ state: "idle", message: "" });
  const progress = Math.round(((step + 1) / steps.length) * 100);
  const update = (event) => { const { name, type, checked, value } = event.target; setValues((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); setErrors((current) => ({ ...current, [name]: "" })); };
  const validate = (target) => { const next = {}; const required = (name, label) => { if (!String(values[name] || "").trim()) next[name] = `${label} is required.`; }; if (target === 0) { required("companyName", "Company Name"); required("contactPerson", "Contact Person"); required("email", "Business Email"); required("phone", "Phone Number"); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) next.email = "Enter a valid business email address."; } if (target === 1) required("industry", "Industry"); if (target === 2) { required("category", "Training Category"); required("objectives", "Training Objectives"); } if (target === 3 && values.participants && (!/^\d+$/.test(values.participants) || Number(values.participants) < 1)) next.participants = "Enter at least one participant."; if (target === 6 && !values.consent) next.consent = "Consent is required before submitting."; setErrors(next); return Object.keys(next).length === 0; };
  const error = (name) => errors[name] ? <span className="proposal-field-error" role="alert">{errors[name]}</span> : null;
  const review = useMemo(() => [["Company", values.companyName], ["Contact", values.contactPerson], ["Industry", values.industry], ["Training", values.category], ["Programme", values.programme], ["Participants", values.participants], ["Location", values.location], ["Preferred month", values.month]], [values]);
  async function submit(event) { event.preventDefault(); if (!validate(6)) return; setStatus({ state: "sending", message: "Sending your request securely..." }); try { const response = await fetch("/api/request-proposal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, formStartedAt: Date.now() - 5000 }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "We could not send your request. Please try again."); router.push("/request-proposal/success"); } catch (submissionError) { setStatus({ state: "error", message: submissionError.message }); } }

  return <form className="proposal-form proposal-wizard" onSubmit={submit} noValidate>
    <div className="proposal-wizard-header"><div><span className="eyebrow">Step {step + 1} of {steps.length}</span><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p></div><strong>{progress}%</strong></div>
    <div className="proposal-wizard-progress" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100} aria-label={`Proposal progress: ${progress}%`}><span style={{ width: `${progress}%` }} /></div>
    {step === 0 && <div className="proposal-form-grid wizard-fields"><label>Company Name *<input name="companyName" value={values.companyName} onChange={update} autoComplete="organization" aria-invalid={Boolean(errors.companyName)} />{error("companyName")}</label><label>Contact Person *<input name="contactPerson" value={values.contactPerson} onChange={update} autoComplete="name" aria-invalid={Boolean(errors.contactPerson)} />{error("contactPerson")}</label><label>Job Title<input name="jobTitle" value={values.jobTitle} onChange={update} autoComplete="organization-title" /></label><label>Business Email *<input name="email" type="email" value={values.email} onChange={update} autoComplete="email" aria-invalid={Boolean(errors.email)} />{error("email")}</label><label>Phone Number *<input name="phone" type="tel" value={values.phone} onChange={update} autoComplete="tel" aria-invalid={Boolean(errors.phone)} />{error("phone")}</label></div>}
    {step === 1 && <div className="wizard-choice-grid">{industries.map((industry) => <label className={`wizard-choice ${values.industry === industry ? "selected" : ""}`} key={industry}><input type="radio" name="industry" value={industry} checked={values.industry === industry} onChange={update} />{industry}</label>)}{error("industry")}</div>}
    {step === 2 && <div className="wizard-fields"><label>Training Category *<select name="category" value={values.category} onChange={update}><option value="">Select a category</option>{categories.map((category) => <option key={category}>{category}</option>)}</select>{error("category")}</label><label>Specific Programme<input name="programme" value={values.programme} onChange={update} placeholder="e.g. Working at Height" /></label><label>Training Objectives *<textarea name="objectives" value={values.objectives} onChange={update} rows="5" placeholder="What would you like the programme to achieve?" />{error("objectives")}</label></div>}
    {step === 3 && <div className="wizard-fields"><label>Number of Participants<input name="participants" type="number" min="1" value={values.participants} onChange={update} placeholder="e.g. 20" />{error("participants")}</label><label>Budget Range (Optional)<input name="budget" value={values.budget} onChange={update} placeholder="Optional" /></label></div>}
    {step === 4 && <div className="wizard-fields"><label>Training Location<input name="location" value={values.location} onChange={update} placeholder="City, site or facility" /></label><label>Additional Notes<textarea name="notes" value={values.notes} onChange={update} rows="5" placeholder="Share other useful requirements or context." /></label></div>}
    {step === 5 && <div className="wizard-fields"><label>Preferred Month<input name="month" type="month" value={values.month} onChange={update} /></label><p className="wizard-note">The selected month is an initial preference only. Our team will confirm availability with you.</p></div>}
    {step === 6 && <div className="wizard-review"><dl>{review.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Not provided"}</dd></div>)}</dl><label className="proposal-consent"><input name="consent" type="checkbox" checked={values.consent} onChange={update} /> <span>I confirm that the information provided is accurate and may be used by TERAS UNIVERSAL to respond to this enquiry.</span></label>{error("consent")}</div>}
    {Object.keys(errors).length > 0 && <p className="proposal-form-error-summary" role="alert">Please review the highlighted fields before continuing.</p>}{status.state === "error" && <p className="proposal-form-error-summary" role="alert">{status.message}</p>}
    <div className="proposal-wizard-actions">{step > 0 && <button className="btn btn-outline" type="button" onClick={() => { setErrors({}); setStep((current) => current - 1); }}>Back</button>}{step < steps.length - 1 ? <button className="btn btn-gold" type="button" onClick={() => validate(step) && setStep((current) => current + 1)}>Continue <span aria-hidden="true">&rarr;</span></button> : <button className="btn btn-gold proposal-submit" type="submit" disabled={status.state === "sending"}>{status.state === "sending" ? "Sending..." : "Submit Proposal Request"} <span aria-hidden="true">&rarr;</span></button>}</div>
    {status.state === "sending" && <p className="proposal-form-status" role="status">{status.message}</p>}
  </form>;
}
