/**
 * Dependency-free ZIP writer (STORE method, no compression) + CRC-32.
 *
 * The npm registry is firewalled in this project's build sandbox, so we cannot
 * add `jszip`/`archiver`. This tiny writer produces a valid .zip using only
 * Node's Buffer — enough to bundle the self-contained HTML certificates
 * generated by the Automation Centre's Bulk Certificate Download.
 *
 * STORE (method 0) means files are stored uncompressed. That's fine here: the
 * payloads are small HTML documents and the win is a single download instead of
 * many. Runs in the Node.js runtime (Buffer required) — not Edge.
 */

// --- CRC-32 (IEEE 802.3), table-driven ------------------------------------
const CRC_TABLE: number[] = (() => {
  const t: number[] = new Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

export function crc32(buf: Buffer): number {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

export interface ZipEntry {
  /** Path inside the archive, e.g. "certificates/TU-CERT-2026-000001.html". */
  name: string;
  /** File contents (string is treated as UTF-8). */
  data: string | Buffer;
}

/**
 * Build a .zip archive (STORE) from a list of entries and return the raw bytes.
 * DOS date/time are fixed (constant) so output is deterministic and to avoid
 * relying on the current clock.
 */
export function createZip(entries: ZipEntry[]): Buffer {
  const DOS_TIME = 0; // 00:00:00
  const DOS_DATE = (1 << 5) | 1; // 1980-01-01 (year bits 0 = 1980, month 1, day 1)

  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBuf = Buffer.from(entry.name, "utf8");
    const dataBuf = typeof entry.data === "string" ? Buffer.from(entry.data, "utf8") : entry.data;
    const crc = crc32(dataBuf);
    const size = dataBuf.length;

    // --- Local file header (30 bytes + name) ---
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0); // signature
    local.writeUInt16LE(20, 4);         // version needed
    local.writeUInt16LE(0x0800, 6);     // flags: bit 11 = UTF-8 filename
    local.writeUInt16LE(0, 8);          // method 0 (STORE)
    local.writeUInt16LE(DOS_TIME, 10);
    local.writeUInt16LE(DOS_DATE, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(size, 18);      // compressed size (== uncompressed for STORE)
    local.writeUInt32LE(size, 22);      // uncompressed size
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);         // extra length
    localParts.push(local, nameBuf, dataBuf);

    // --- Central directory header (46 bytes + name) ---
    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0); // signature
    central.writeUInt16LE(20, 4);         // version made by
    central.writeUInt16LE(20, 6);         // version needed
    central.writeUInt16LE(0x0800, 8);     // flags: UTF-8
    central.writeUInt16LE(0, 10);         // method
    central.writeUInt16LE(DOS_TIME, 12);
    central.writeUInt16LE(DOS_DATE, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(size, 20);
    central.writeUInt32LE(size, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt16LE(0, 30);         // extra length
    central.writeUInt16LE(0, 32);         // comment length
    central.writeUInt16LE(0, 34);         // disk number start
    central.writeUInt16LE(0, 36);         // internal attributes
    central.writeUInt32LE(0, 38);         // external attributes
    central.writeUInt32LE(offset, 42);    // local header offset
    centralParts.push(central, nameBuf);

    offset += local.length + nameBuf.length + dataBuf.length;
  }

  const centralBuf = Buffer.concat(centralParts);
  const localBuf = Buffer.concat(localParts);

  // --- End of central directory record (22 bytes) ---
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);          // signature
  eocd.writeUInt16LE(0, 4);                   // disk number
  eocd.writeUInt16LE(0, 6);                   // disk with central dir
  eocd.writeUInt16LE(entries.length, 8);      // entries on this disk
  eocd.writeUInt16LE(entries.length, 10);     // total entries
  eocd.writeUInt32LE(centralBuf.length, 12);  // central dir size
  eocd.writeUInt32LE(localBuf.length, 16);    // central dir offset
  eocd.writeUInt16LE(0, 20);                  // comment length

  return Buffer.concat([localBuf, centralBuf, eocd]);
}

/** Make a string safe to use as a filename inside the archive. */
export function safeFileName(s: string): string {
  return (s || "file").replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 120) || "file";
}
