import Image from "next/image";
import MobileNav from "../../components/MobileNav";
import MegaNav from "../../components/MegaNav";
import Footer from "../../components/Footer";
import CredentialGrid from "../../components/public/CredentialGrid";
import CorporateTrainingCta from "../../components/public/CorporateTrainingCta";
import DeliveryOptions from "../../components/public/DeliveryOptions";
import TrustStrip from "../../components/public/TrustStrip";
import styles from "../../components/public/public-phase-two.module.css";
import { accreditations, confirmedFacts, leadership, partners } from "../../data/companyProfile";
import { industries } from "../../data/industries";
import { approvedSuccessStories, approvedTestimonials } from "../../data/successStories";

export const metadata = { title: "Corporate Training", description: "Corporate, in-house and onsite industrial safety, technical competency and workforce development solutions from TERAS UNIVERSAL.", alternates: { canonical: "/corporate-training" }, openGraph: { title: "Corporate Training | TERAS UNIVERSAL", description: "Custom industrial safety, competency and workforce development solutions for Malaysian organisations.", url: "/corporate-training" } };

const pillars = [["Industrial Safety Training", "Practical learning designed around workplace hazards, controls and safe task execution."], ["Technical Competency Development", "Structured development that connects knowledge, guided practice and job-relevant capability."], ["Competency Assessment", "Theoretical and practical evaluation according to the requirements of the programme."], ["Industrial Consultancy", "Practical advisory support for organisations reviewing operational weaknesses and improvement priorities."], ["Corporate & In-House Training", "Programme scope and delivery arrangements shaped around one organisation or workforce group."], ["Workforce Development", "Role-focused development aligned with workforce, project and operational requirements."]];
const process = [["Understand Requirements", "Discuss workforce profile, operating environment, objectives and delivery needs."], ["Identify Capability Needs", "Clarify the relevant training, competency or assessment requirement."], ["Design the Arrangement", "Plan programme scope, delivery method, timing and practical requirements."], ["Deliver Training or Assessment", "Provide structured theory, practical learning or assessment as required."], ["Follow Up", "Record completion or certification where the programme requirements apply."]];

export default function CorporateTrainingPage() {
  const director = leadership[0];
  return <main className="corporate-training-page">
    <header className="site-header"><div className="container nav-wrap"><a className="brand" href="/" aria-label="TERAS UNIVERSAL home"><Image src="/teras-universal-logo.png" alt="TERAS UNIVERSAL logo" width={220} height={140} priority sizes="154px" /></a><MegaNav /><MobileNav basePath="/" /></div></header>
    <section className="services-hero" aria-labelledby="corporate-training-title"><div className="container services-hero-grid"><div className="services-hero-copy"><span className="eyebrow">Corporate Training</span><h1 id="corporate-training-title">Build competence around your workforce and operating realities.</h1><p>TERAS UNIVERSAL supports organisations with industrial safety training, technical competency development, consultancy and workforce solutions shaped around practical workplace needs.</p><div className="hero-actions"><a className="btn btn-primary" href="/request-proposal?source=corporate-training">Request Corporate Training</a><a className="btn btn-outline" href="https://wa.me/60195193834?text=Hi%20TERAS%2C%20saya%20ingin%20bertanya%20tentang%20latihan%20korporat." target="_blank" rel="noreferrer">Talk to TERAS</a></div></div><figure className="services-hero-media"><Image src="/images/temp-ai-corporate-scene-11.webp" alt="Industrial training consultation visual." width={1200} height={800} priority sizes="(max-width: 920px) 100vw, 52vw" /></figure></div></section>
    <section className="services-standard-section"><div className="container services-standard-grid"><div><span className="eyebrow">Corporate Capability</span><h2>Training, assessment and advice that connect with the work.</h2></div><div><p>Corporate arrangements can be shaped around workforce roles, operational requirements, participant profiles and preferred delivery methods.</p><TrustStrip facts={confirmedFacts.slice(0, 4)} /></div></div></section>
    <section className="training-programmes-section"><div className="container"><div className="section-heading"><span className="eyebrow">Corporate Solutions</span><h2>One conversation, relevant capability options.</h2><p>Start with the requirement, then build the most suitable training, assessment or advisory arrangement.</p></div><div className={styles.solutionGrid}>{pillars.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="services-process-section"><div className="container"><div className="section-heading"><span className="eyebrow">Customisation Process</span><h2>A disciplined route from requirement to delivery.</h2></div><div className={styles.processGrid}>{process.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="training-delivery-section"><div className="container"><div className="section-heading"><span className="eyebrow">Delivery Options</span><h2>Arrange learning around the team and the workplace.</h2></div><DeliveryOptions /></div></section>
    <section className="industries-hub-grid-section"><div className="container"><div className="section-heading"><span className="eyebrow">Industries Served</span><h2>Relevant for safety-critical operations.</h2><p>Explore the sector context, relevant programmes and corporate enquiry path for the industries TERAS supports.</p></div><div className={styles.industryLinkGrid}>{industries.map((industry) => <a key={industry.slug} href={`/industries/${industry.slug}`}><span>Industry</span><h3>{industry.name}</h3><p>{industry.summary}</p><b>View industry solutions →</b></a>)}</div></div></section>
    <section className="about-accred-section"><div className="container"><div className="section-heading"><span className="eyebrow">Why TERAS</span><h2>Verified credentials for corporate conversations.</h2></div><CredentialGrid credentials={accreditations} /></div></section>
    <section className="about-leadership-section"><div className="container"><div className="section-heading"><span className="eyebrow">Industry Experience</span><h2>Leadership grounded in industrial practice.</h2></div><div className={styles.proofGrid}><article><span>Established</span><strong>2012</strong><p>TERAS UNIVERSAL has been incorporated since 2012.</p></article>{director && <article><span>{director.role}</span><strong>{director.name}</strong><p>{director.credential || "Industry training and competency background."}</p></article>}<article><span>Certificate Verification</span><strong>Verify issued certificates</strong><p><a href="/verify">Use the TERAS public certificate verification page →</a></p></article></div></div></section>
    {partners.length > 0 && <section className="about-partners-section"><div className="container"><div className="section-heading"><span className="eyebrow">Approved Partner References</span><h2>Organisations TERAS collaborates with.</h2></div><div className={styles.partnerGrid}>{partners.map((partner) => <article key={partner.name}><h3>{partner.name}</h3><p>{partner.text}</p></article>)}</div></div></section>}
    {approvedSuccessStories.length > 0 && <section className="training-programmes-section"><div className="container"><div className="section-heading"><span className="eyebrow">Approved Project Proof</span><h2>Selected work and outcomes.</h2></div></div></section>}
    {approvedTestimonials.length > 0 && <section className="training-programmes-section"><div className="container"><div className="section-heading"><span className="eyebrow">Approved Testimonials</span><h2>What organisations say.</h2></div></div></section>}
    <section className="container"><CorporateTrainingCta source="corporate-training-final" title="Ready to discuss your workforce requirements?" text="Share your operating context, workforce needs and preferred arrangement. TERAS will use that as the starting point for the conversation." /></section>
    <Footer />
  </main>;
}
