"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "../../../../../lib/supabase/server";
import { requireModuleAccess, requireRole } from "../../../../../lib/auth/session";
import { participantImportRowSchema } from "../../../../../lib/validation/schemas";
import { normalizeIdentityNumber } from "../../../../../lib/identity";

export interface RawRow { [key: string]: string }
export interface AnalyzedRow {
  index: number;
  status: "ok" | "invalid" | "duplicate";
  reason?: string;
  data?: Record<string, string>;
}
export interface ImportAnalysis {
  rows: AnalyzedRow[];
  summary: { total: number; ok: number; invalid: number; duplicate: number };
}

function normaliseGender(g?: string) {
  const s = (g ?? "").trim().toLowerCase();
  if (s.startsWith("m")) return "Male";
  if (s.startsWith("f")) return "Female";
  return "";
}
function normaliseDate(d?: string) {
  const s = (d ?? "").trim();
  if (!s) return "";
  // Accept YYYY-MM-DD or DD/MM/YYYY.
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  const m = s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);
  if (m) return `${m[3]}-${m[2].padStart(2, "0")}-${m[1].padStart(2, "0")}`;
  return s; // let DB reject if truly invalid
}

/**
 * Analyse parsed rows WITHOUT writing: validate each, detect duplicates by
 * IC/Passport (both within the batch and against the database), and return a
 * per-row status + summary for the preview screen. Invalid rows are skipped.
 */
export async function analyzeImport(raw: RawRow[]): Promise<ImportAnalysis> {
  await requireRole("admin");
  await requireModuleAccess("participants");
  const supabase = await createSupabaseServerClient();

  // Existing ICs (live rows) for duplicate detection.
  const { data: existing } = await supabase.from("participants").select("ic_passport_no").is("deleted_at", null).limit(100000);
  const existingIc = new Set((existing ?? []).map((r: any) => normalizeIdentityNumber(r.ic_passport_no)));

  const seenInBatch = new Set<string>();
  const rows: AnalyzedRow[] = raw.map((r, index) => {
    const candidate = {
      full_name: r.full_name ?? r["Full Name"] ?? "",
      ic_passport_no: r.ic_passport_no ?? r["IC / Passport"] ?? r["IC/Passport"] ?? "",
      company: r.company ?? r["Company"] ?? "",
      phone: r.phone ?? r["Phone"] ?? "",
      email: r.email ?? r["Email"] ?? "",
      nationality: r.nationality ?? r["Nationality"] ?? "",
      position: r.position ?? r["Position"] ?? "",
      gender: normaliseGender(r.gender ?? r["Gender"]),
      date_of_birth: normaliseDate(r.date_of_birth ?? r["Date of Birth"]),
      address: r.address ?? r["Address"] ?? "",
      emergency_contact_name: r.emergency_contact_name ?? r["Emergency Contact"] ?? "",
      emergency_contact_phone: r.emergency_contact_phone ?? r["Emergency Phone"] ?? "",
    };
    const parsed = participantImportRowSchema.safeParse(candidate);
    if (!parsed.success) {
      return { index, status: "invalid", reason: parsed.error.issues[0]?.message ?? "Invalid row" };
    }
    const ic = normalizeIdentityNumber(parsed.data.ic_passport_no);
    if (existingIc.has(ic) || seenInBatch.has(ic)) {
      return { index, status: "duplicate", reason: "IC / Passport already exists", data: parsed.data };
    }
    seenInBatch.add(ic);
    return { index, status: "ok", data: parsed.data };
  });

  const summary = {
    total: rows.length,
    ok: rows.filter((r) => r.status === "ok").length,
    invalid: rows.filter((r) => r.status === "invalid").length,
    duplicate: rows.filter((r) => r.status === "duplicate").length,
  };
  return { rows, summary };
}

/**
 * Commit an import: re-analyses (never trust the client) and inserts only the
 * "ok" rows. Participant IDs are generated by the DB trigger. Writes one audit
 * entry summarising the import.
 */
export async function commitImport(raw: RawRow[]): Promise<{ inserted: number; skipped: number; message?: string }> {
  await requireRole("admin");
  const analysis = await analyzeImport(raw);
  const toInsert = analysis.rows.filter((r) => r.status === "ok").map((r) => r.data!);
  if (toInsert.length === 0) return { inserted: 0, skipped: analysis.summary.total };

  const supabase = await createSupabaseServerClient();
  const payload = toInsert.map((d) => ({
    ...d,
    email: d.email || null,
    gender: d.gender || null,
    date_of_birth: d.date_of_birth || null,
    status: "registered" as const,
  }));
  const { error, count } = await supabase.from("participants").insert(payload, { count: "exact" });
  if (error) return { inserted: 0, skipped: analysis.summary.total, message: error.message };

  const inserted = count ?? toInsert.length;
  const skippedDup = analysis.summary.duplicate;
  const skippedInvalid = analysis.summary.invalid;

  await supabase.rpc("log_event" as never, {
    p_action: "import",
    p_entity_type: "participants",
    p_summary: `Imported ${inserted} participants (${skippedInvalid} invalid, ${skippedDup} duplicate skipped)`,
  } as never);

  // Record in the Automation Centre (import history).
  await supabase.from("automation_runs").insert({
    run_type: "bulk_import",
    status: skippedInvalid + skippedDup === 0 ? "success" : "partial",
    summary: `Participant import: ${inserted} added, ${skippedInvalid} invalid, ${skippedDup} duplicate`,
    total_count: analysis.summary.total,
    success_count: inserted,
    skipped_count: skippedDup,
    failed_count: skippedInvalid,
    params: {},
    result: { invalid: skippedInvalid, duplicate: skippedDup },
  });

  revalidatePath("/admin/participants");
  revalidatePath("/admin/automation");
  return { inserted, skipped: skippedInvalid + skippedDup };
}
