"use client";

import { useMemo, useState } from "react";
import { downloadCsv, extractCertificate, validateRows } from "../../../lib/bulkCertificates";

export default function BulkPdfImport({ busy, onImport }) {
  const [files, setFiles] = useState([]); const [rows, setRows] = useState([]); const [useOcr, setUseOcr] = useState(true); const [processing, setProcessing] = useState(false); const [progress, setProgress] = useState(0); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const ready = useMemo(() => rows.filter((row) => row.parse_status === "ready"), [rows]);
  async function processFiles() { setProcessing(true); setProgress(0); setError(""); setMessage(""); const parsed = []; try { for (let index = 0; index < files.length; index += 1) { parsed.push(await extractCertificate(files[index], { useOcr, onProgress: (part) => setProgress(Math.round(((index + part) / files.length) * 100)) })); setProgress(Math.round(((index + 1) / files.length) * 100)); } setRows(validateRows(parsed)); setMessage(`${parsed.length} PDF selesai diproses. Semak baris bertanda kuning.`); } catch (err) { setError(err.message || "PDF tidak dapat diproses."); } finally { setProcessing(false); } }
  function updateRow(index, field, value) { setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value, parse_status: "ready", error_message: "" } : row)); }
  return <section className="admin-panel admin-bulk-panel"><div className="admin-bulk-heading"><div><span className="eyebrow">PDF PROCESSING</span><h2>Import banyak PDF sijil</h2><p>Ekstrak data automatik, semak rekod, kemudian import ke database.</p></div><span className="admin-bulk-count">{rows.length} baris</span></div><div className="admin-bulk-controls"><input type="file" accept="application/pdf,.pdf" multiple onChange={(event) => { setFiles(Array.from(event.target.files || [])); setRows([]); setMessage(""); }} disabled={processing || busy} /><label className="admin-check"><input type="checkbox" checked={useOcr} onChange={(event) => setUseOcr(event.target.checked)} /> OCR untuk PDF scan</label><button className="btn btn-primary" type="button" onClick={processFiles} disabled={!files.length || processing || busy}>{processing ? `Memproses ${progress}%…` : `Proses ${files.length || ""} PDF`}</button>{rows.length > 0 && <><button className="btn btn-outline" type="button" onClick={() => downloadCsv(rows)}>Muat turun CSV</button><button className="btn btn-primary" type="button" onClick={() => onImport(ready, rows)} disabled={!ready.length || processing || busy}>Import {ready.length} rekod</button></>}</div>{message && <p className="admin-success">{message}</p>}{error && <p className="verify-error" role="alert">{error}</p>}{rows.length > 0 && <p className="admin-bulk-summary"><strong>{ready.length} sedia</strong> · {rows.length - ready.length} perlu semakan · Data peribadi kekal di browser sehingga import disahkan.</p>}{rows.length > 0 && <div className="admin-table-wrap admin-bulk-table-wrap"><table><thead><tr><th>Fail</th><th>Nama peserta</th><th>No. sijil</th><th>Kursus</th><th>Tarikh</th><th>Status</th></tr></thead><tbody>{rows.map((row, index) => <tr className={row.parse_status !== "ready" ? "admin-bulk-review" : ""} key={`${row.source_file}-${index}`}><td title={row.error_message || row.source_file}>{row.source_file}</td><td><input value={row.participant_name} onChange={(event) => updateRow(index, "participant_name", event.target.value)} /></td><td><input value={row.certificate_no} onChange={(event) => updateRow(index, "certificate_no", event.target.value)} /></td><td><input value={row.course_name} onChange={(event) => updateRow(index, "course_name", event.target.value)} /></td><td><input type="date" value={row.course_date} onChange={(event) => updateRow(index, "course_date", event.target.value)} /></td><td><span className={`admin-status admin-status-${row.parse_status}`}>{row.parse_status === "ready" ? "Sedia" : "Semak"}</span><small>{row.error_message}</small></td></tr>)}</tbody></table></div>}</section>;
}
