<#
    approval-runner.ps1 - human approval gate and controlled commit
    preparation for the TERAS AI Engineering Orchestrator. Dot-sourced by
    teras-agent.ps1, which must set $RepoRoot, $AiDir, $CurrentTaskPath
    before sourcing this file. Depends on functions from agent-router.ps1
    and qa-runner.ps1 also being sourced first.

    Hard safety invariants enforced in this file, not just documented:
    - staging ever only uses `git add -- <exact paths>`, never `.` or `-A`
    - pre-existing staged changes are detected and block automated commit,
      never unstaged automatically
    - `git commit` only runs after a literal "YES" typed at a live prompt
    - push, deploy, and migration-apply are never invoked anywhere below
#>

function Get-CommitMessage {
    param($State)

    $desc = $State.Description.Trim()
    $prefix = "fix"
    $rest = $desc

    if ($desc -match '(?i)^(fix|correct|resolve|repair|refine|patch|harden)\b\s*(.*)$') {
        $prefix = "fix"; $rest = $Matches[2]
    } elseif ($desc -match '(?i)^(add|create|implement|introduce|build)\b\s*(.*)$') {
        $prefix = "feat"; $rest = $Matches[2]
    } elseif ($desc -match '(?i)^(refactor)\b\s*(.*)$') {
        $prefix = "refactor"; $rest = $Matches[2]
    } elseif ($desc -match '(?i)^(document|docs)\b\s*(.*)$') {
        $prefix = "docs"; $rest = $Matches[2]
    } elseif ($desc -match '(?i)^(test)\b\s*(.*)$') {
        $prefix = "test"; $rest = $Matches[2]
    } elseif ($State.Category -eq "Feature") {
        $prefix = "feat"; $rest = $desc
    }

    $rest = $rest.Trim()
    if ($rest.Length -eq 0) { $rest = $desc }
    $rest = $rest.Substring(0, 1).ToLowerInvariant() + $rest.Substring(1)
    $rest = $rest.TrimEnd('.')

    return "$prefix`: $rest"
}

function Save-ApprovalRecord {
    param($State, [string]$Decision, [string]$Reason)

    $path = Join-Path $AiDir "APPROVAL.md"
    $approvedFilesText = if (@($State.TaskGeneratedFiles).Count -gt 0) { (@($State.TaskGeneratedFiles) | ForEach-Object { "- $_" }) -join "`n" } else { "- (none recorded)" }
    $qaSummary = "Git Diff Check=$($State.QA.GitDiffCheck.Result), TypeScript=$($State.QA.TypeScript.Result), Tests=$($State.QA.Tests.Result), Build=$($State.QA.Build.Result)"
    $reasonLine = if ($Reason) { "Reason: $Reason" } else { "" }

    $content = @"
# APPROVAL.md

> Generated by ``tools/approval-runner.ps1``. Applies ONLY to the task below - not a standing or global permission. A new task always starts back at Human Decision: PENDING.

Task ID: $($State.TaskId)
Approved At: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Approved State: $Decision
$reasonLine

Approved Files:
$approvedFilesText

QA Summary: $qaSummary
Review Verdict: $($State.ReviewVerdict)

Commit Allowed: $(if ($Decision -eq "APPROVED" -or $Decision -eq "PREVIEW_APPROVED") { "YES (this task only, subject to -PrepareCommit/-Commit's own checks)" } else { "NO" })
Push Allowed: $(if ($Decision -eq "APPROVED" -or $Decision -eq "PREVIEW_APPROVED") { "YES (this task only, subject to -PreparePush's own eligibility/branch checks)" } else { "NO" })
Deploy Allowed: NO
Migration Apply Allowed: NO

Preview Approved: $(if ($State.PreviewApproved) { "YES" } else { "NO" })
Preview Approved At: $(if ($State.PreviewApprovedAt) { $State.PreviewApprovedAt } else { "(none)" })
Preview Commit SHA: $(if ($State.PreviewCommitSha) { $State.PreviewCommitSha } else { "(none)" })
Preview Deployment ID: $(if ($State.PreviewDeploymentIdApproved) { $State.PreviewDeploymentIdApproved } else { "(none)" })
Production Deployment Allowed: NO

Release Approved: $(if ($State.ReleaseApproved) { "YES" } else { "NO" })
Release Approved At: $(if ($State.ReleaseApprovedAt) { $State.ReleaseApprovedAt } else { "(none)" })
Approved PR: $(if ($State.ReleaseApprovedPr) { $State.ReleaseApprovedPr } else { "(none)" })
Approved Commit SHA: $(if ($State.ReleaseApprovedCommitSha) { $State.ReleaseApprovedCommitSha } else { "(none)" })
Approved Target Branch: $(if ($State.PrTargetBranch) { $State.PrTargetBranch } else { "(none)" })
Approved Production Scope: $(if ($State.ReleaseApproved) { "This task's release only - not a standing production permission" } else { "(none)" })
Migration Approval: $(if ($State.MigrationDetected) { "NOT APPROVED (migration apply is not implemented in this phase - always blocks release)" } else { "N/A - no migration in this task" })
Environment Change Approval: $(if ($State.EnvironmentChangeDetected) { "Flagged for human review in RELEASE_REPORT.md - not separately auto-approved" } else { "N/A - no environment change in this task" })
"@

    Set-Content -Path $path -Value $content -Encoding utf8
}

function Invoke-Approve {
    $state = Get-TaskState
    if ($state.State -eq "NONE") {
        Write-Host ""
        Write-Host "No current task found. Nothing to approve."
        Write-Host ""
        return
    }

    # Phase 4: once a task has reached PREVIEW_READY, -Approve records
    # approval of the PREVIEW (Invoke-ApprovePreview, preview-runner.ps1)
    # rather than re-approving the already-committed task.
    if ($state.State -eq "PREVIEW_READY") {
        Invoke-ApprovePreview -State $state
        return
    }

    if ($state.State -ne "AWAITING_APPROVAL") {
        Write-Host ""
        Write-Host "APPROVAL BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Task is not awaiting approval (current state: $($state.State))."
        Write-Host ""
        return
    }

    if ($state.ScopeCheck -eq "FAIL") {
        Write-Host ""
        Write-Host "APPROVAL BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Unauthorized file changes detected."
        Write-Host ""
        return
    }

    if ($state.ScopeCheck -eq "NOT_CONFIGURED") {
        Write-Host ""
        Write-Host "APPROVAL BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Scope has not been verified for this task (Allowed Files was never configured)."
        Write-Host ""
        return
    }

    if (Test-QaHasBlockingFailure -QaResults $state.QA) {
        Write-Host ""
        Write-Host "APPROVAL BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Blocking QA failure detected."
        Write-Host ""
        return
    }

    $reviewMandatory = ($state.Reviewer -eq "Codex" -or $state.Reviewer -eq "Human")
    if ($reviewMandatory -and $state.ReviewVerdict -notin @("PASS", "PASS_WITH_NOTES")) {
        Write-Host ""
        Write-Host "APPROVAL BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Mandatory independent review has not completed."
        Write-Host ""
        return
    }

    $state.State = "APPROVED"
    $state.HumanDecision = "APPROVED"
    Save-TaskState -State $state
    Save-ApprovalRecord -State $state -Decision "APPROVED"

    Write-Host ""
    Write-Host "Task APPROVED."
    Write-Host "Commit Allowed: YES (this task only)  |  Push: NO  |  Deploy: NO  |  Migration Apply: NO"
    Write-Host "Next: teras-agent -PrepareCommit"
    Write-Host ""
}

function Invoke-Reject {
    $state = Get-TaskState
    if ($state.State -eq "NONE") {
        Write-Host ""
        Write-Host "No current task found. Nothing to reject."
        Write-Host ""
        return
    }

    $state.State = "BLOCKED"
    $state.HumanDecision = "REJECTED"
    Save-TaskState -State $state
    Save-ApprovalRecord -State $state -Decision "REJECTED"

    Write-Host ""
    Write-Host "Task rejected."
    Write-Host ""
    Write-Host "No files were reverted."
    Write-Host "No commit created."
    Write-Host "No push performed."
    Write-Host "No deployment performed."
    Write-Host ""
    Write-Host "The human should decide what happens to the working tree."
    Write-Host ""
}

function Show-CommitPreview {
    param($State)

    $message = Get-CommitMessage -State $State

    Write-Host ""
    Write-Host "========================================"
    Write-Host "TERAS COMMIT PREPARATION"
    Write-Host "========================================"
    Write-Host ""
    Write-Host "Task ID:"
    Write-Host $State.TaskId
    Write-Host ""
    Write-Host "Approved files:"
    Write-Host ""
    if (@($State.TaskGeneratedFiles).Count -eq 0) {
        Write-Host "- (none recorded - nothing to commit)"
    } else {
        foreach ($f in @($State.TaskGeneratedFiles)) { Write-Host "- $f" }
    }
    Write-Host ""
    Write-Host "Excluded pre-existing changes:"
    Write-Host ""
    if (@($State.PreExistingFiles).Count -eq 0) {
        Write-Host "- (none)"
    } else {
        foreach ($f in @($State.PreExistingFiles)) { Write-Host "- $f" }
    }
    Write-Host ""
    Write-Host "Proposed commit message:"
    Write-Host ""
    Write-Host $message
    Write-Host ""
    Write-Host "Commit:"
    Write-Host "NOT EXECUTED"
    Write-Host ""

    return $message
}

function Invoke-PrepareCommit {
    $state = Get-TaskState
    if ($state.State -eq "NONE") {
        Write-Host ""
        Write-Host "No current task found."
        Write-Host ""
        return
    }

    if ($state.State -notin @("APPROVED", "COMMIT_READY")) {
        Write-Host ""
        Write-Host "PREPARE COMMIT BLOCKED"
        Write-Host ""
        Write-Host "Reason:"
        Write-Host "Task must be APPROVED first (current state: $($state.State))."
        Write-Host ""
        return
    }

    $message = Show-CommitPreview -State $state
    $state.CommitMessage = $message
    $state.State = "COMMIT_READY"
    Save-TaskState -State $state
}

function Get-StagedFiles {
    Push-Location $RepoRoot
    try {
        return @(git diff --cached --name-only)
    } finally {
        Pop-Location
    }
}

# Best-effort, not a substitute for real secret scanning - only exists to
# stop an anomalous report (one of our own generated .ai/*.md files, which
# should never contain a secret per BUSINESS_RULES.md/CLAUDE.md's logging
# rules) from being copied into the audit-trail snapshot unexamined.
function Test-SecretPattern {
    param([string]$Content)

    $patterns = @(
        'SUPABASE_SERVICE_ROLE_KEY',
        'service_role',
        'sk-[A-Za-z0-9]{10,}',
        'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}',
        'AKIA[0-9A-Z]{16}',
        '(?i)password\s*[:=]\s*\S+',
        'BEGIN (RSA|EC|OPENSSH) PRIVATE KEY',
        '-----BEGIN CERTIFICATE-----'
    )
    foreach ($p in $patterns) {
        if ($Content -match $p) { return $true }
    }
    return $false
}

function New-HistorySnapshot {
    param($State)

    $historyDir = Join-Path $AiDir "history\$($State.TaskId)"
    $reportFiles = @(
        "CURRENT_TASK.md", "IMPLEMENTATION_REPORT.md", "REVIEW_REPORT.md", "FINAL_REPORT.md", "APPROVAL.md",
        "PREVIEW_REPORT.md", "PR_REPORT.md", "RELEASE_REPORT.md", "ROLLBACK_PLAN.md"
    )

    foreach ($name in $reportFiles) {
        $src = Join-Path $AiDir $name
        if (Test-Path $src) {
            $content = Get-Content -Path $src -Raw
            if (Test-SecretPattern -Content $content) {
                Write-Host ""
                Write-Host "HISTORY SNAPSHOT BLOCKED"
                Write-Host ""
                Write-Host "Potential sensitive information detected in $name. Snapshot skipped;"
                Write-Host "the commit itself is not affected by this check."
                Write-Host ""
                return $false
            }
        }
    }

    New-Item -ItemType Directory -Path $historyDir -Force | Out-Null
    foreach ($name in $reportFiles) {
        $src = Join-Path $AiDir $name
        $dst = Join-Path $historyDir $name
        if (Test-Path $src) {
            Copy-Item -Path $src -Destination $dst -Force
        } else {
            Set-Content -Path $dst -Value "NOT_REQUIRED" -Encoding utf8
        }
    }
    Write-Host "History snapshot saved to .ai/history/$($State.TaskId)/"
    return $true
}

function Invoke-Commit {
    $state = Get-TaskState
    if ($state.State -eq "NONE") {
        Write-Host ""
        Write-Host "No current task found."
        Write-Host ""
        return
    }

    if ($state.State -notin @("APPROVED", "COMMIT_READY")) {
        Write-Host ""
        Write-Host "COMMIT BLOCKED"
        Write-Host ""
        Write-Host "Current state:"
        Write-Host $state.State
        Write-Host ""
        Write-Host "Required state:"
        Write-Host "APPROVED or COMMIT_READY"
        Write-Host ""
        return
    }

    $message = Show-CommitPreview -State $state
    $state.CommitMessage = $message

    $approvedFiles = @($state.TaskGeneratedFiles)
    if ($approvedFiles.Count -eq 0) {
        Write-Host "No task-generated files recorded. Nothing to commit."
        return
    }

    $preStaged = Get-StagedFiles
    if ($preStaged.Count -gt 0) {
        Write-Host ""
        Write-Host "PRE-EXISTING STAGED CHANGES DETECTED"
        Write-Host ""
        foreach ($f in $preStaged) { Write-Host "- $f" }
        Write-Host ""
        Write-Host "COMMIT BLOCKED"
        Write-Host "Human intervention required."
        Write-Host ""
        return
    }

    Push-Location $RepoRoot
    try {
        git add -- $approvedFiles

        Write-Host ""
        git diff --cached --stat
        Write-Host ""
        $checkOutput = git diff --cached --check 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host "git diff --cached --check reported issues:"
            Write-Host ($checkOutput -join "`n")
            Write-Host ""
            Write-Host "COMMIT BLOCKED"
            Write-Host "Resolve the issues above, then retry. Staged files were left as-is."
            Write-Host ""
            return
        }

        $stagedSet = @(Get-StagedFiles) | Sort-Object -Unique
        $approvedSet = $approvedFiles | Sort-Object -Unique
        $mismatch = Compare-Object -ReferenceObject $approvedSet -DifferenceObject $stagedSet
        if ($mismatch) {
            Write-Host ""
            Write-Host "COMMIT BLOCKED"
            Write-Host ""
            Write-Host "Staged scope does not match approved scope."
            Write-Host ""
            return
        }

        Write-Host ""
        Write-Host "========================================"
        Write-Host "FINAL COMMIT CONFIRMATION"
        Write-Host "========================================"
        Write-Host ""
        Write-Host "Task:"
        Write-Host $state.Description
        Write-Host ""
        Write-Host "Files:"
        Write-Host $approvedFiles.Count
        Write-Host ""
        foreach ($f in $approvedFiles) { Write-Host "- $f" }
        Write-Host ""
        Write-Host "Commit message:"
        Write-Host $message
        Write-Host ""
        Write-Host "QA:"
        Write-Host $(if (Test-QaHasBlockingFailure -QaResults $state.QA) { "FAIL" } else { "PASS" })
        Write-Host ""
        Write-Host "Independent Review:"
        Write-Host $state.ReviewVerdict
        Write-Host ""
        Write-Host "This action will create a local Git commit."
        Write-Host ""
        Write-Host "It will NOT:"
        Write-Host "- push"
        Write-Host "- deploy"
        Write-Host "- apply migrations"
        Write-Host "- modify production data"
        Write-Host ""

        $confirm = Read-Host "Type YES to create commit"
        if ($confirm -cne "YES") {
            Write-Host ""
            Write-Host "Commit cancelled. No commit was created."
            Write-Host "The approved files remain staged for your review; unstage manually if desired."
            Write-Host ""
            return
        }

        New-HistorySnapshot -State $state | Out-Null

        git commit -m $message
        if ($LASTEXITCODE -ne 0) {
            Write-Host ""
            Write-Host "git commit failed. Staged files were left as-is for inspection."
            Write-Host ""
            return
        }

        $sha = (git rev-parse HEAD).Trim()
        Write-Host ""
        git show --stat --oneline HEAD
        Write-Host ""
        git status --short
        Write-Host ""

        $state.CommitSha = $sha
        $state.State = "COMPLETE"
        Save-TaskState -State $state
        Save-ApprovalRecord -State $state -Decision "APPROVED"

        Write-Host "Commit Status: CREATED"
        Write-Host "Commit SHA: $sha"
        Write-Host "Commit Message: $message"
        Write-Host ""
        Write-Host "Local Engineering Task: COMPLETE"
        Write-Host "Production Deployment: NOT PERFORMED"
        Write-Host ""
    } finally {
        Pop-Location
    }
}

function Show-DeployBlocked {
    Write-Host ""
    Write-Host "PRODUCTION ACTION BLOCKED"
    Write-Host ""
    Write-Host "Phase 4 supports preview deployment only."
    Write-Host ""
    Write-Host "AUTO_PRODUCTION_DEPLOY=false, AUTO_MERGE=false, AUTO_MIGRATION_APPLY=false."
    Write-Host "Deploy Allowed: NO"
    Write-Host ""
}

function Show-Status {
    $state = Get-TaskState

    Write-Host ""
    Write-Host "========================================"
    Write-Host "TERAS AI TASK STATUS"
    Write-Host "========================================"
    Write-Host ""

    if ($state.State -eq "NONE") {
        Write-Host "No current task."
        Write-Host ""
        return
    }

    Write-Host "Task ID:"
    Write-Host $state.TaskId
    Write-Host ""
    Write-Host "Task:"
    Write-Host $state.Description
    Write-Host ""
    Write-Host "State:"
    Write-Host $state.State
    Write-Host ""
    Write-Host "Risk:"
    Write-Host $state.Risk
    Write-Host ""
    Write-Host "Implementer:"
    Write-Host "$($state.Implementer) / $($state.ImplementerModel)"
    Write-Host ""
    Write-Host "Codex Review:"
    Write-Host $state.ReviewVerdict
    Write-Host ""
    Write-Host "Scope:"
    Write-Host $state.ScopeCheck
    Write-Host ""
    Write-Host "QA:"
    Write-Host $(if (Test-QaHasBlockingFailure -QaResults $state.QA) { "FAIL" } else { "PASS" })
    Write-Host ""
    Write-Host "Human Approval:"
    Write-Host $state.HumanDecision
    Write-Host ""
    Write-Host "Commit:"
    Write-Host $(if ($state.CommitSha) { "CREATED ($($state.CommitSha.Substring(0, [Math]::Min(8, $state.CommitSha.Length))))" } else { "NOT CREATED" })
    Write-Host ""
    Write-Host "Push:"
    Write-Host $(if ($state.State -in @("PUSHED", "PREVIEW_DEPLOYING", "PREVIEW_VERIFYING", "PREVIEW_READY", "PREVIEW_APPROVED")) { "PUSHED ($($state.PushTarget))" } elseif ($state.State -eq "PUSH_BLOCKED") { "BLOCKED" } else { "NOT PERFORMED" })
    Write-Host ""
    Write-Host "Preview:"
    Write-Host "$($state.PreviewStatus) / verification: $($state.PreviewVerificationStatus)$(if ($state.PreviewUrl) { " ($($state.PreviewUrl))" })"
    Write-Host ""
    Write-Host "Deploy:"
    Write-Host "NOT PERFORMED (production deployment is not implemented)"
    Write-Host ""
    Write-Host "Migration:"
    Write-Host "NOT APPLIED"
    Write-Host ""
}
